import Providers from "@/utils/provider";
import { Inter } from "next/font/google";
import "./home.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Products-list",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
